"""Destination knowledge base used to synthesise training discussions.

Each POI: (label, location, icon, slots, english aliases, chinese alias)
  icon  - one of the app's activity icon keys (lib/repositories/trip_repository.dart)
  slots - parts of the day the place makes sense in:
          B breakfast, M morning, L lunch, A afternoon, E evening, D dinner, N night
  aliases - how people actually call the place in chat. The model has to map
          these back to the official label.

OSAKA and KOTA KINABALU are never used for training: they form the
"unseen destination" test split, which measures whether the tuned model
generalises beyond the places it was trained on.
"""

HELD_OUT = {"Osaka, Japan", "Kota Kinabalu, Malaysia"}

DESTINATIONS = {
    "Penang, Malaysia": {
        "airport": "Penang International Airport (PEN)",
        "pois": [
            ("Kek Lok Si Temple", "Air Itam", "place", "MA", ["kek lok si"], "极乐寺"),
            ("Penang Hill", "Air Itam", "place", "MAE", ["bukit bendera", "penang hill"], "升旗山"),
            ("Chew Jetty", "Weld Quay, George Town", "place", "MAE", ["chew jetty", "clan jetty"], "姓周桥"),
            ("George Town Street Art", "Armenian Street", "place", "MA", ["street art", "armenian street murals"], "壁画街"),
            ("Cheong Fatt Tze Mansion", "Leith Street", "place", "MA", ["blue mansion"], "蓝屋"),
            ("Gurney Drive Hawker Centre", "Gurney Drive", "food", "DN", ["gurney hawker", "gurney drive"], "新关仔角"),
            ("Penang Road Famous Teochew Chendul", "Jalan Penang", "food", "A", ["penang road cendol", "the famous chendul"], "槟榔律煎蕊"),
            ("Toh Soon Cafe", "Campbell Street", "food", "B", ["toh soon"], "多春茶座"),
            ("Nasi Kandar Line Clear", "Jalan Penang", "food", "LDN", ["line clear"], ""),
            ("Batu Ferringhi Night Market", "Batu Ferringhi", "shopping", "N", ["batu ferringhi pasar malam", "ferringhi night market"], "峇都丁宜夜市"),
            ("Gurney Plaza", "Gurney Drive", "shopping", "AE", ["gurney plaza"], "合您广场"),
            ("Entopia Butterfly Farm", "Teluk Bahang", "activity", "MA", ["entopia", "butterfly farm"], "蝴蝶公园"),
            ("ESCAPE Penang", "Teluk Bahang", "activity", "MA", ["escape", "escape theme park"], ""),
            ("Siam Road Char Koay Teow", "Siam Road", "food", "LD", ["siam road ckt"], "暹罗路炒粿条"),
            ("Kimberley Street Food Night Market", "Lebuh Kimberley", "food", "DN", ["kimberley street"], "汕头街"),
        ],
    },
    "Kuala Lumpur, Malaysia": {
        "airport": "Kuala Lumpur International Airport (KUL)",
        "pois": [
            ("Petronas Twin Towers", "KLCC", "place", "MAEN", ["klcc", "twin towers"], "双峰塔"),
            ("Batu Caves", "Gombak", "place", "M", ["batu caves"], "黑风洞"),
            ("Jalan Alor Food Street", "Bukit Bintang", "food", "DN", ["jalan alor"], "阿罗街"),
            ("Pavilion Kuala Lumpur", "Bukit Bintang", "shopping", "AE", ["pavilion"], "柏威年"),
            ("Central Market", "Jalan Hang Kasturi", "shopping", "MA", ["pasar seni", "central market"], "中央艺术坊"),
            ("Petaling Street", "Chinatown", "shopping", "AEN", ["petaling street", "chinatown"], "茨厂街"),
            ("KL Tower", "Bukit Nanas", "place", "AEN", ["menara kl", "kl tower"], "吉隆坡塔"),
            ("Thean Hou Temple", "Robson Heights", "place", "MAE", ["thean hou"], "天后宫"),
            ("Village Park Restaurant", "Damansara Uptown", "food", "BL", ["village park nasi lemak", "village park"], ""),
            ("Aquaria KLCC", "KLCC", "activity", "MA", ["aquaria"], "水族馆"),
            ("Merdeka Square", "Jalan Raja", "place", "ME", ["dataran merdeka"], "独立广场"),
            ("Sunway Lagoon", "Bandar Sunway", "activity", "MA", ["sunway lagoon"], ""),
            ("Lot 10 Hutong Food Court", "Bukit Bintang", "food", "LD", ["lot 10 hutong", "hutong"], "十号胡同"),
            ("Islamic Arts Museum Malaysia", "Jalan Lembah Perdana", "place", "MA", ["islamic arts museum"], ""),
            ("Kwai Chai Hong", "Lorong Panggung", "place", "MAE", ["kwai chai hong"], "鬼仔巷"),
        ],
    },
    "Melaka, Malaysia": {
        "airport": None,
        "pois": [
            ("Jonker Street Night Market", "Jonker Walk", "shopping", "N", ["jonker street", "jonker walk"], "鸡场街"),
            ("A Famosa", "Bandar Hilir", "place", "MAE", ["a famosa", "porta de santiago"], ""),
            ("St. Paul's Hill", "Bandar Hilir", "place", "MAE", ["st paul hill", "st paul's church"], "圣保罗山"),
            ("The Stadthuys", "Dutch Square", "place", "MA", ["red house", "stadthuys", "dutch square"], "红屋"),
            ("Melaka River Cruise", "Melaka River", "activity", "EN", ["river cruise"], "马六甲河游船"),
            ("Chung Wah Chicken Rice Ball", "Jonker Walk", "food", "L", ["chung wah", "chicken rice ball"], "中华茶室"),
            ("Jonker 88", "Jonker Walk", "food", "A", ["jonker 88 cendol"], ""),
            ("Melaka Straits Mosque", "Pulau Melaka", "place", "E", ["masjid selat", "floating mosque"], "海上清真寺"),
            ("Baba & Nyonya Heritage Museum", "Jalan Tun Tan Cheng Lock", "place", "MA", ["baba nyonya museum"], "峇峇娘惹博物馆"),
            ("Klebang Original Coconut Shake", "Klebang", "food", "A", ["klebang coconut shake", "coconut shake"], "椰子雪"),
            ("Menara Taming Sari", "Bandar Hilir", "activity", "AEN", ["taming sari tower"], ""),
            ("Capitol Satay Celup", "Lorong Bukit Cina", "food", "D", ["capitol satay celup", "satay celup"], "沙爹朱律"),
            ("The Shore Sky Tower", "Jalan Persisiran Bunga Raya", "place", "EN", ["sky tower", "the shore"], ""),
        ],
    },
    "Langkawi, Malaysia": {
        "airport": "Langkawi International Airport (LGK)",
        "pois": [
            ("Langkawi Sky Bridge", "Gunung Mat Cincang", "place", "MA", ["sky bridge"], "天空之桥"),
            ("Langkawi Cable Car (SkyCab)", "Oriental Village", "activity", "MA", ["skycab", "cable car"], "缆车"),
            ("Pantai Cenang", "Pantai Cenang", "place", "AE", ["cenang beach", "pantai cenang"], "珍南海滩"),
            ("Eagle Square", "Kuah", "place", "ME", ["dataran lang", "eagle square"], "巨鹰广场"),
            ("Kilim Geoforest Park Mangrove Tour", "Kilim", "activity", "MA", ["kilim mangrove tour", "mangrove tour"], "红树林"),
            ("Island Hopping Tour", "Pulau Dayang Bunting", "activity", "M", ["island hopping"], "跳岛游"),
            ("Tanjung Rhu Beach", "Tanjung Rhu", "place", "AE", ["tanjung rhu"], ""),
            ("Telaga Tujuh Waterfalls", "Jalan Telaga Tujuh", "place", "MA", ["seven wells waterfall", "telaga tujuh"], "七仙井"),
            ("Underwater World Langkawi", "Pantai Cenang", "activity", "MA", ["underwater world"], "海底世界"),
            ("Duty Free Shopping at Kuah Town", "Kuah", "shopping", "AE", ["kuah duty free", "duty free shopping"], "免税店"),
            ("Langkawi Sunset Cruise", "Telaga Harbour", "activity", "E", ["sunset cruise"], "日落游船"),
            ("Wonderland Food Store", "Kuah", "food", "D", ["wonderland seafood", "wonderland"], ""),
            ("Tomato Nasi Kandar", "Pantai Cenang", "food", "BLDN", ["tomato nasi kandar"], ""),
            ("Yellow Beach Cafe", "Pantai Cenang", "food", "LD", ["yellow cafe"], ""),
            ("Makam Mahsuri", "Mawat", "place", "MA", ["mahsuri tomb", "makam mahsuri"], ""),
        ],
    },
    "Singapore": {
        "airport": "Singapore Changi Airport (SIN)",
        "pois": [
            ("Gardens by the Bay", "Marina Bay", "place", "AEN", ["gbtb", "gardens by the bay"], "滨海湾花园"),
            ("Marina Bay Sands SkyPark", "Marina Bay", "place", "EN", ["mbs", "marina bay sands"], "金沙"),
            ("Merlion Park", "Marina Bay", "place", "MAE", ["merlion"], "鱼尾狮"),
            ("Universal Studios Singapore", "Sentosa", "activity", "MA", ["uss", "universal studios"], "环球影城"),
            ("Sentosa Island", "Sentosa", "place", "MAE", ["sentosa"], "圣淘沙"),
            ("Singapore Zoo", "Mandai", "activity", "MA", ["the zoo"], "动物园"),
            ("Night Safari", "Mandai", "activity", "N", ["night safari"], "夜间动物园"),
            ("Maxwell Food Centre", "Chinatown", "food", "LD", ["maxwell"], "麦士威"),
            ("Lau Pa Sat", "Raffles Quay", "food", "DN", ["lau pa sat", "satay street"], "老巴刹"),
            ("Orchard Road", "Orchard", "shopping", "AE", ["orchard"], "乌节路"),
            ("Chinatown", "Chinatown", "place", "MAE", ["chinatown"], "牛车水"),
            ("Haji Lane", "Kampong Glam", "shopping", "AE", ["haji lane", "kampong glam"], ""),
            ("Jewel Changi Airport", "Changi", "shopping", "MAE", ["jewel"], "星耀樟宜"),
            ("Ya Kun Kaya Toast", "Far East Square", "food", "B", ["ya kun"], "亚坤"),
            ("Clarke Quay", "Singapore River", "place", "EN", ["clarke quay"], "克拉码头"),
            ("Singapore Botanic Gardens", "Tanglin", "place", "M", ["botanic gardens"], "植物园"),
        ],
    },
    "Bangkok, Thailand": {
        "airport": "Suvarnabhumi Airport (BKK)",
        "pois": [
            ("The Grand Palace", "Phra Nakhon", "place", "M", ["grand palace"], "大皇宫"),
            ("Wat Arun", "Bangkok Yai", "place", "MAE", ["wat arun", "temple of dawn"], "郑王庙"),
            ("Wat Pho", "Phra Nakhon", "place", "MA", ["wat pho", "reclining buddha"], "卧佛寺"),
            ("Chatuchak Weekend Market", "Chatuchak", "shopping", "MA", ["chatuchak", "jj market"], "洽图洽"),
            ("Siam Paragon", "Siam", "shopping", "AE", ["siam paragon"], "暹罗百丽宫"),
            ("Platinum Fashion Mall", "Pratunam", "shopping", "MA", ["platinum mall", "platinum"], "水门市场"),
            ("ICONSIAM", "Khlong San", "shopping", "AEN", ["iconsiam", "icon siam"], ""),
            ("Jodd Fairs Night Market", "Rama 9", "food", "N", ["jodd fairs"], "乔德夜市"),
            ("Yaowarat Road (Chinatown)", "Samphanthawong", "food", "DN", ["yaowarat", "chinatown"], "耀华力路"),
            ("Khao San Road", "Phra Nakhon", "place", "N", ["khao san"], "考山路"),
            ("Chao Phraya River Dinner Cruise", "Chao Phraya River", "activity", "D", ["dinner cruise", "chao phraya cruise"], "湄南河游船"),
            ("Thipsamai Pad Thai", "Maha Chai Road", "food", "D", ["thipsamai"], ""),
            ("Jim Thompson House Museum", "Pathum Wan", "place", "MA", ["jim thompson house"], ""),
            ("Damnoen Saduak Floating Market", "Ratchaburi", "activity", "M", ["floating market"], "水上市场"),
            ("Mahanakhon SkyWalk", "Silom", "place", "EN", ["mahanakhon"], ""),
            ("After You Dessert Cafe", "Siam Square", "food", "A", ["after you"], ""),
        ],
    },
    "Bali, Indonesia": {
        "airport": "Ngurah Rai International Airport (DPS)",
        "pois": [
            ("Tanah Lot Temple", "Tabanan", "place", "E", ["tanah lot"], "海神庙"),
            ("Uluwatu Temple", "Uluwatu", "place", "E", ["uluwatu"], "乌鲁瓦图"),
            ("Tegalalang Rice Terrace", "Ubud", "place", "M", ["tegalalang", "rice terrace"], "梯田"),
            ("Sacred Monkey Forest Sanctuary", "Ubud", "place", "MA", ["monkey forest"], "猴子森林"),
            ("Ubud Art Market", "Ubud", "shopping", "MA", ["ubud market"], "乌布市场"),
            ("Seminyak Beach", "Seminyak", "place", "AE", ["seminyak"], ""),
            ("Kuta Beach", "Kuta", "place", "AE", ["kuta"], "库塔海滩"),
            ("Jimbaran Bay Seafood Dinner", "Jimbaran", "food", "D", ["jimbaran seafood", "jimbaran"], "金巴兰"),
            ("Bali Swing", "Ubud", "activity", "MA", ["bali swing"], "秋千"),
            ("Tirta Empul Temple", "Tampaksiring", "place", "MA", ["tirta empul"], "圣泉寺"),
            ("Nusa Penida Day Trip", "Nusa Penida", "activity", "M", ["nusa penida"], "佩妮达岛"),
            ("Waterbom Bali", "Kuta", "activity", "MA", ["waterbom"], ""),
            ("Potato Head Beach Club", "Seminyak", "food", "ED", ["potato head"], ""),
            ("Warung Babi Guling Ibu Oka", "Ubud", "food", "L", ["ibu oka", "babi guling"], ""),
            ("Lempuyang Temple (Gates of Heaven)", "Karangasem", "place", "M", ["gates of heaven", "lempuyang"], "天堂之门"),
            ("Sisterfields Cafe", "Seminyak", "food", "BL", ["sisterfields"], ""),
            ("Bebek Tepi Sawah", "Ubud", "food", "LD", ["bebek tepi sawah"], "脏鸭餐"),
        ],
    },
    "Tokyo, Japan": {
        "airport": "Narita International Airport (NRT)",
        "pois": [
            ("Senso-ji Temple", "Asakusa", "place", "MA", ["sensoji", "asakusa temple"], "浅草寺"),
            ("Tokyo Skytree", "Sumida", "place", "AEN", ["skytree"], "晴空塔"),
            ("Shibuya Crossing", "Shibuya", "place", "AEN", ["shibuya crossing", "shibuya scramble"], "涩谷十字路口"),
            ("Meiji Shrine", "Harajuku", "place", "M", ["meiji jingu"], "明治神宫"),
            ("Takeshita Street", "Harajuku", "shopping", "A", ["harajuku", "takeshita"], "竹下通"),
            ("Tsukiji Outer Market", "Tsukiji", "food", "BL", ["tsukiji"], "筑地市场"),
            ("Tokyo Disneyland", "Urayasu", "activity", "M", ["disneyland", "disney"], "迪士尼"),
            ("teamLab Planets", "Toyosu", "activity", "AE", ["teamlab"], ""),
            ("Akihabara Electric Town", "Akihabara", "shopping", "AE", ["akihabara", "akiba"], "秋叶原"),
            ("Shinjuku Omoide Yokocho", "Shinjuku", "food", "DN", ["omoide yokocho"], "思出横丁"),
            ("Ichiran Ramen Shibuya", "Shibuya", "food", "LDN", ["ichiran"], "一兰拉面"),
            ("Tokyo Tower", "Minato", "place", "EN", ["tokyo tower"], "东京塔"),
            ("Ginza", "Chuo", "shopping", "AE", ["ginza"], "银座"),
            ("Ueno Park", "Taito", "place", "MA", ["ueno"], "上野公园"),
            ("Shibuya Sky", "Shibuya", "place", "E", ["shibuya sky"], ""),
        ],
    },
    "Seoul, South Korea": {
        "airport": "Incheon International Airport (ICN)",
        "pois": [
            ("Gyeongbokgung Palace", "Jongno", "place", "MA", ["gyeongbokgung", "the palace"], "景福宫"),
            ("Bukchon Hanok Village", "Jongno", "place", "MA", ["bukchon"], "北村韩屋村"),
            ("N Seoul Tower", "Namsan", "place", "EN", ["namsan tower", "n tower"], "南山塔"),
            ("Myeongdong Shopping Street", "Myeongdong", "shopping", "AEN", ["myeongdong"], "明洞"),
            ("Hongdae", "Mapo", "shopping", "AEN", ["hongdae"], "弘大"),
            ("Gwangjang Market", "Jongno", "food", "LD", ["gwangjang market"], "广藏市场"),
            ("Lotte World", "Jamsil", "activity", "MA", ["lotte world"], "乐天世界"),
            ("Nami Island", "Chuncheon", "activity", "M", ["nami island"], "南怡岛"),
            ("Starfield COEX Mall", "Gangnam", "shopping", "AE", ["coex", "starfield library"], ""),
            ("Insadong", "Jongno", "shopping", "MA", ["insadong"], "仁寺洞"),
            ("Dongdaemun Design Plaza", "Dongdaemun", "place", "EN", ["ddp", "dongdaemun"], "东大门"),
            ("Cheonggyecheon Stream", "Jongno", "place", "EN", ["cheonggyecheon"], "清溪川"),
            ("Tosokchon Samgyetang", "Jongno", "food", "LD", ["tosokchon"], "土俗村"),
            ("Ihwa Mural Village", "Jongno", "place", "MA", ["ihwa mural village"], ""),
            ("Yeouido Hangang Park", "Yeouido", "place", "EN", ["han river", "hangang park"], "汉江公园"),
        ],
    },
    "Taipei, Taiwan": {
        "airport": "Taiwan Taoyuan International Airport (TPE)",
        "pois": [
            ("Taipei 101 Observatory", "Xinyi", "place", "AEN", ["taipei 101", "101"], "台北101"),
            ("Shilin Night Market", "Shilin", "food", "N", ["shilin"], "士林夜市"),
            ("Raohe Street Night Market", "Songshan", "food", "N", ["raohe"], "饶河夜市"),
            ("Chiang Kai-shek Memorial Hall", "Zhongzheng", "place", "MA", ["cks memorial"], "中正纪念堂"),
            ("Jiufen Old Street", "Ruifang", "place", "AE", ["jiufen"], "九份"),
            ("Shifen Old Street", "Pingxi", "activity", "MA", ["shifen", "sky lantern"], "十分"),
            ("Ximending", "Wanhua", "shopping", "AEN", ["ximending", "ximen"], "西门町"),
            ("National Palace Museum", "Shilin", "place", "MA", ["palace museum"], "故宫博物院"),
            ("Elephant Mountain", "Xinyi", "activity", "E", ["xiangshan", "elephant mountain"], "象山"),
            ("Din Tai Fung (Xinyi Road)", "Da'an", "food", "LD", ["din tai fung", "dtf"], "鼎泰丰"),
            ("Yongkang Street", "Da'an", "food", "LA", ["yongkang street"], "永康街"),
            ("Beitou Hot Spring", "Beitou", "activity", "MA", ["beitou"], "北投温泉"),
            ("Longshan Temple", "Wanhua", "place", "MAE", ["longshan temple"], "龙山寺"),
            ("Fuhang Soy Milk", "Zhongzheng", "food", "B", ["fuhang", "fu hang dou jiang"], "阜杭豆浆"),
            ("Tamsui Old Street", "Tamsui", "place", "AE", ["tamsui", "danshui"], "淡水老街"),
            ("Yehliu Geopark", "Wanli", "place", "M", ["yehliu"], "野柳"),
        ],
    },
    "Hong Kong": {
        "airport": "Hong Kong International Airport (HKG)",
        "pois": [
            ("Victoria Peak", "The Peak", "place", "AEN", ["the peak", "peak tram"], "太平山"),
            ("Hong Kong Disneyland", "Lantau Island", "activity", "M", ["disneyland", "disney"], "迪士尼"),
            ("Ngong Ping 360 & Tian Tan Buddha", "Lantau Island", "activity", "MA", ["big buddha", "ngong ping"], "天坛大佛"),
            ("Star Ferry", "Tsim Sha Tsui", "activity", "AEN", ["star ferry"], "天星小轮"),
            ("Avenue of Stars", "Tsim Sha Tsui", "place", "EN", ["avenue of stars", "symphony of lights"], "星光大道"),
            ("Temple Street Night Market", "Jordan", "shopping", "N", ["temple street"], "庙街"),
            ("Ladies' Market", "Mong Kok", "shopping", "AEN", ["ladies market", "mong kok"], "女人街"),
            ("Tim Ho Wan (Sham Shui Po)", "Sham Shui Po", "food", "BL", ["tim ho wan"], "添好运"),
            ("Australia Dairy Company", "Jordan", "food", "B", ["australia dairy"], "澳洲牛奶公司"),
            ("Ocean Park", "Wong Chuk Hang", "activity", "MA", ["ocean park"], "海洋公园"),
            ("Lan Kwai Fong", "Central", "place", "N", ["lkf"], "兰桂坊"),
            ("Mak's Noodle", "Central", "food", "LD", ["mak's noodle", "maks wonton noodle"], "麦奀云吞面"),
            ("Wong Tai Sin Temple", "Wong Tai Sin", "place", "MA", ["wong tai sin"], "黄大仙"),
            ("Kam's Roast Goose", "Wan Chai", "food", "LD", ["kam's roast goose", "kams"], "甘牌烧鹅"),
            ("Tai Kwun", "Central", "place", "AE", ["tai kwun"], "大馆"),
            ("Harbour City", "Tsim Sha Tsui", "shopping", "AE", ["harbour city"], "海港城"),
        ],
    },
    "Ho Chi Minh City, Vietnam": {
        "airport": "Tan Son Nhat International Airport (SGN)",
        "pois": [
            ("Ben Thanh Market", "District 1", "shopping", "MAE", ["ben thanh"], "滨城市场"),
            ("War Remnants Museum", "District 3", "place", "MA", ["war museum"], "战争遗迹博物馆"),
            ("Cu Chi Tunnels", "Cu Chi", "activity", "M", ["cu chi"], "古芝地道"),
            ("Notre-Dame Cathedral Basilica of Saigon", "District 1", "place", "MA", ["notre dame"], "红教堂"),
            ("Saigon Central Post Office", "District 1", "place", "MA", ["central post office", "post office"], "中央邮局"),
            ("Bui Vien Walking Street", "District 1", "place", "N", ["bui vien"], ""),
            ("Independence Palace", "District 1", "place", "MA", ["reunification palace", "independence palace"], "独立宫"),
            ("Mekong Delta Day Tour", "My Tho", "activity", "M", ["mekong delta", "mekong tour"], "湄公河"),
            ("Pho Hoa Pasteur", "District 3", "food", "BL", ["pho hoa"], ""),
            ("Banh Mi Huynh Hoa", "District 1", "food", "LA", ["banh mi huynh hoa", "huynh hoa"], ""),
            ("Saigon Skydeck (Bitexco Tower)", "District 1", "place", "EN", ["bitexco", "skydeck"], ""),
            ("The Cafe Apartments", "District 1", "food", "AE", ["cafe apartment", "42 nguyen hue"], "咖啡公寓"),
            ("Nguyen Hue Walking Street", "District 1", "place", "EN", ["nguyen hue"], ""),
            ("Ben Nghe Street Food Market", "District 1", "food", "DN", ["ben nghe street food", "street food market"], ""),
            ("Saigon Square", "District 1", "shopping", "AE", ["saigon square"], ""),
        ],
    },
    # ---------------- held out: never seen in training ----------------
    "Osaka, Japan": {
        "airport": "Kansai International Airport (KIX)",
        "pois": [
            ("Osaka Castle", "Chuo", "place", "MA", ["osaka castle"], "大阪城"),
            ("Dotonbori", "Namba", "food", "DN", ["dotonbori", "glico sign"], "道顿堀"),
            ("Universal Studios Japan", "Konohana", "activity", "M", ["usj"], "环球影城"),
            ("Shinsaibashi-suji Shopping Street", "Chuo", "shopping", "AE", ["shinsaibashi"], "心斋桥"),
            ("Kuromon Ichiba Market", "Nippombashi", "food", "BL", ["kuromon market", "kuromon"], "黑门市场"),
            ("Umeda Sky Building", "Kita", "place", "EN", ["umeda sky"], "梅田蓝天大厦"),
            ("Shinsekai & Tsutenkaku Tower", "Naniwa", "place", "AEN", ["shinsekai", "tsutenkaku"], "通天阁"),
            ("Osaka Aquarium Kaiyukan", "Minato", "activity", "MA", ["kaiyukan", "the aquarium"], "海游馆"),
            ("Nara Park Day Trip", "Nara", "activity", "M", ["nara", "deer park"], "奈良"),
            ("Sumiyoshi Taisha", "Sumiyoshi", "place", "MA", ["sumiyoshi shrine"], "住吉大社"),
            ("Ichiran Ramen Dotonbori", "Namba", "food", "LDN", ["ichiran"], "一兰拉面"),
            ("Rinku Premium Outlets", "Izumisano", "shopping", "MA", ["rinku outlet"], "临空城outlet"),
            ("Harukas 300 Observatory", "Abeno", "place", "EN", ["harukas"], ""),
            ("Kani Doraku Dotonbori", "Namba", "food", "LD", ["kani doraku", "the crab restaurant"], "蟹道乐"),
        ],
    },
    "Kota Kinabalu, Malaysia": {
        "airport": "Kota Kinabalu International Airport (BKI)",
        "pois": [
            ("Kinabalu Park", "Kundasang", "place", "M", ["kinabalu park"], "神山公园"),
            ("Desa Dairy Farm", "Kundasang", "place", "MA", ["desa cattle farm", "desa farm"], "牧场"),
            ("Tunku Abdul Rahman Marine Park Island Hopping", "Jesselton Point", "activity", "M", ["island hopping", "manukan sapi"], "跳岛"),
            ("Tanjung Aru Beach Sunset", "Tanjung Aru", "place", "E", ["tanjung aru"], "丹绒亚路"),
            ("Gaya Street Sunday Market", "Gaya Street", "shopping", "M", ["gaya street"], "加雅街"),
            ("Kota Kinabalu City Mosque", "Likas Bay", "place", "MAE", ["floating mosque", "masjid bandaraya"], "水上清真寺"),
            ("Filipino Market", "Jalan Tun Fuad Stephens", "shopping", "EN", ["filipino market", "handicraft market"], "菲律宾市场"),
            ("Welcome Seafood Restaurant", "Asia City", "food", "D", ["welcome seafood"], "大茄来"),
            ("Yee Fung Laksa", "Gaya Street", "food", "BL", ["yee fung"], "怡丰叻沙"),
            ("Mari Mari Cultural Village", "Inanam", "activity", "MA", ["mari mari"], ""),
            ("Klias River Firefly Cruise", "Beaufort", "activity", "EN", ["firefly tour", "klias"], "萤火虫"),
            ("Signal Hill Observatory", "Signal Hill", "place", "E", ["signal hill"], ""),
            ("Imago Shopping Mall", "KK Times Square", "shopping", "AE", ["imago"], ""),
            ("Fook Yuen Cafe", "Gaya Street", "food", "B", ["fook yuen"], "富源"),
        ],
    },
}
