// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxXTqdMBZcmSzk3VnR3I1Z_QvozhAAreo',
    appId: '1:1020854066179:web:ea9339cd6449d030208236',
    messagingSenderId: '1020854066179',
    projectId: 'voya-f69f0',
    authDomain: 'voya-f69f0.firebaseapp.com',
    storageBucket: 'voya-f69f0.firebasestorage.app',
    measurementId: 'G-0WZKRWZD00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvXPu-JELI5GnC_xcfZx4uKLc8sR9FD9A',
    appId: '1:1020854066179:android:03f2aa6779f87a96208236',
    messagingSenderId: '1020854066179',
    projectId: 'voya-f69f0',
    storageBucket: 'voya-f69f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF3u1O6wzjdhkH-qmCdkeK0WF0fIV5360',
    appId: '1:1020854066179:ios:897743ceac8b4491208236',
    messagingSenderId: '1020854066179',
    projectId: 'voya-f69f0',
    storageBucket: 'voya-f69f0.firebasestorage.app',
    iosBundleId: 'my.fyp.voya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF3u1O6wzjdhkH-qmCdkeK0WF0fIV5360',
    appId: '1:1020854066179:ios:897743ceac8b4491208236',
    messagingSenderId: '1020854066179',
    projectId: 'voya-f69f0',
    storageBucket: 'voya-f69f0.firebasestorage.app',
    iosBundleId: 'my.fyp.voya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxXTqdMBZcmSzk3VnR3I1Z_QvozhAAreo',
    appId: '1:1020854066179:web:8298689e85b2e380208236',
    messagingSenderId: '1020854066179',
    projectId: 'voya-f69f0',
    authDomain: 'voya-f69f0.firebaseapp.com',
    storageBucket: 'voya-f69f0.firebasestorage.app',
    measurementId: 'G-L11N7J7Z7W',
  );
}
